#!/bin/bash

__USER=$USER

# Get super user privileges
if [[ $EUID != 0 ]]; then
    sudo "$0" "$@"
    exit $?
fi

this_path=$PWD
install_path=/tmp/install/
mkdir -p $install_path && cd $install_path

function find::folder {
	if [ ! -d $1 ]; then
		echo " [x] $(basename $1) not found..."
		return 1
	fi
	echo " [x] $(basename $1) found..."
	return 0
}

function find::file {
	if [ ! -f $1 ]; then
		echo " [x] $(basename $1) not found..."
		return 1
	fi
	echo " [x] $(basename $1) found..."
	return 0
}

function find::pkg {
	if ! pkg-config --exists $1; then
		echo " [x] $1 not found..."
		return 1
	fi
	echo " [x] $1 found..."
	return 0
}

function import::git {
	if [ ! -d $(basename $1) ]; then
		git clone $1
	fi
	echo -n $(basename $1)
}

function install::cmake {
	read path
	cd $path
	mkdir -p build
	cd build
	cmake -DCMAKE_INSTALL::LIBDIR=lib .. 
	make install -j `nproc`
	cd $install_path
}

function install::aria {
    wget http://robots.mobilerobots.com/ARIA/download/current/ARIA-src-2.9.1.tar.gz
    tar -xf ARIA-src-2.9.1.tar.gz
    rm ARIA-src-2.9.1.tar.gz
    cd Aria-src-2.9.1
    make allLibs -j `nproc`
    cp lib/* /usr/local/lib
    mkdir /usr/local/include/Aria
    cp include/* /usr/local/include/Aria
    ldconfig
}

function install::arma {
    wget https://sourceforge.net/projects/arma/files/armadillo-7.900.1.tar.xz
    tar -xf armadillo-7.900.1.tar.xz
    rm armadillo-7.900.1.tar.xz
    cd armadillo-7.900.1
    ./configure
    cmake .
    make -j `nproc`
    make install
    ldconfig
}

function install::zmq {
    read path
    cd $path
    ./autogen.sh
	./configure --with-pgm
    make install -j `nproc`
    ldconfig
    cd $install_path
}

function install::zmqcpp {
	read path
    cd $path
	cp *.hpp /usr/local/include
	cd $install_path
}

function install::code {
    wget https://go.microsoft.com/fwlink/?LinkID=760868 -O visual_studio_code.deb
    dpkg -i  visual_studio_code.deb
}

function install::mobilesim {
    wget http://robots.mobilerobots.com/MobileSim/download/current/mobilesim_0.7.5+ubuntu12_i386.deb
    gdebi --option=APT::Get::force-yes="true" --option=APT::Get::Assume-Yes="true" -n mobilesim_0.7.5+ubuntu12_i386.deb
}

apt-get update && apt-get install -y --ignore-missing \
	build-essential cmake git pkg-config gdebi wget autoconf automake \
    libtool libgtk2.0-dev libopenblas-dev liblapack-dev liblapacke-dev \
    libssl-dev  libkrb5-dev libpgm-dev libpgm-5.*

if ! find::folder /usr/local/include/Aria; then
    install::aria
fi

if ! find::folder /usr/include/armadillo_bits; then
    install::arma
fi

if ! find::pkg msgpack; then
	import::git https://github.com/msgpack/msgpack-c | install::cmake 
fi

if ! find::pkg libzmq; then
    import::git https://github.com/zeromq/libzmq | install::zmq
fi

if ! find::file /usr/local/include/zmq.hpp; then
	import::git https://github.com/zeromq/cppzmq | install::zmqcpp
fi

if ! find::file /usr/local/bin/MobileSim; then
    install::mobilesim
fi

if ! find::file /usr/bin/code; then
    install::code
fi